### ISSUE TITLE
Clicking any brand link on the product_template kanban view results in error

### ISSUE THREAD

**Issue by symbiotech** [OCA/brand#190]
## Module
product_brand

## Describe the bug
Clicking any brand link on the product_template kanban view results in the error bellow:

```
EvalError: Can not evaluate python expression: ([('product_ids', 'in', id)])
Error: Name 'id' is not defined
    at evaluateExpr (http://45.33.98.35/web/assets/0ddd052/web.assets_web.min.js:3029:54)
    at _preprocessAction (http://45.33.98.35/web/assets/0ddd052/web.assets_web.min.js:10127:150)
    at doAction (http://45.33.98.35/web/assets/0ddd052/web.assets_web.min.js:10209:170)
    at async Object.doActionButton (http://45.33.98.35/web/assets/0ddd052/web.assets_web.min.js:10217:196)
    at async execute (http://45.33.98.35/web/assets/0ddd052/web.assets_web.min.js:9843:293)
    at async executeButtonCallback (http://45.33.98.35/web/assets/0ddd052/web.assets_web.min.js:9836:34)
```

## To Reproduce
**Affected versions**:
Odoo 17

1. Navigate to Products - Products section
2. Make sure you are on the Kanban view
3. Click on any product brand link

**Expected behavior**
Action should open a Product Brand page with the filter applied to the selected brand, without throwing an error. Bug seems to have been introduced in [this line](https://github.com/OCA/brand/commit/70b15d6f9998578501b5abbb47e9c84507c22e65#diff-f8bae1353dc5496c9dcb2af7167e462146e3d4a8a156545d6ea05e7cf85b5cb9L24)

**Comment by symbiotech** [comment]
@thaolt99 can you please take a look at this issue and the related pull request?
