### ISSUE TITLE
not found parent view ?

### ISSUE THREAD

**Issue by abyte20** [OCA/brand#59]
Hello,
Does not work in Odoo 13, clean installation with OCA website and ecommerce modules.

If I select "brand_external_layout" on "Settings>Documents" the server return 500 after payment on website store.
In the backend when I generating the sales order, it don't generate the pdf:

Odoo Server Error

Traceback (most recent call last):
  File "/home/usuario/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/usuario/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/usuario/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7fa435ddd160>, 'web.external_layout_standard', ('en_US', False, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuario/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/usuario/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/usuario/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View._read_template at 0x7fa436393280>, frozenset({1, 2, 3, 4, 6, 7, 10, 14, 17, 18, 19, 21, 23, 27, 28, 29, 32, 33, 35, 36, 37, 38, 39, 40, 41, 44, 47, 50, 51, 54, 55, 56, 58, 59, 60, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 81}), 213, ('en_US', False, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 669, in apply_inheritance_specs
    source = apply_inheritance_specs(source, specs_tree,
  File "/home/usuario/odoo/odoo/tools/template_inheritance.py", line 229, in apply_inheritance_specs
    raise ValueError(
ValueError: El elemento '<xpath expr="//t[@t-if='not company']">' no puede ser localizado en la vista padre

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 359, in get_template
    document = options.get('load', self.load)(template, options)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_qweb.py", line 121, in load
    template = env['ir.ui.view'].read_template(name)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 1071, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-33>", line 2, in _read_template
  File "/home/usuario/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 1063, in _read_template
    arch = self.browse(view_id).read_combined(['arch'])['arch']
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 745, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 694, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<xpath expr="//t[@t-if='not company']">' no puede ser localizado en la vista padre

Error context:
View `brand_external_layout`
[view_id: 2340, xml_id: brand_external_report_layout.brand_external_layout, model: n/a, parent_id: 213]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuario/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/usuario/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/usuario/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/usuario/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/usuario/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/usuario/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/usuario/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/usuario/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/usuario/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/usuario/odoo/addons/web/controllers/main.py", line 1327, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/usuario/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/usuario/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/usuario/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/usuario/odoo/odoo/models.py", line 6202, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/usuario/odoo/odoo/models.py", line 5981, in _onchange_eval
    method_res = method(self)
  File "/home/usuario/odoo/addons/mail/wizard/mail_compose_message.py", line 384, in onchange_template_id_wrapper
    values = self.onchange_template_id(self.template_id.id, self.composition_mode, self.model, self.res_id)['value']
  File "/home/usuario/odoo/addons/mail/wizard/mail_compose_message.py", line 405, in onchange_template_id
    values = self.generate_email_for_composer(template_id, [res_id])[res_id]
  File "/home/usuario/odoo/addons/mail/wizard/mail_compose_message.py", line 538, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields=fields)
  File "/home/usuario/odoo/addons/mail/models/mail_template.py", line 437, in generate_email
    result, format = report.render_qweb_pdf([res_id])
  File "/home/usuario/odoo/odoo/addons/base/models/ir_actions_report.py", line 734, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/home/usuario/odoo/odoo/addons/base/models/ir_actions_report.py", line 774, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/home/usuario/odoo/odoo/addons/base/models/ir_actions_report.py", line 548, in render_template
    return view_obj.render_template(template, values)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 1191, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/usuario/odoo/addons/website/models/ir_ui_view.py", line 336, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/usuario/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 1199, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_sale_report_saleorder_15121
  File "<template>", line 2, in body_call_content_15119
  File "<template>", line 3, in foreach_15118
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_sale_report_saleorder_document_15172
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 335, in _compiled_fn
    raise e
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_external_layout_15214
  File "<decorator-gen-54>", line 2, in compile
  File "/home/usuario/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_qweb.py", line 113, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 277, in compile
    element, document = self.get_template(template, options)
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 365, in get_template
    raise QWebException("load could not load template", e, path, name=template)
odoo.addons.base.models.qweb.QWebException: El elemento '<xpath expr="//t[@t-if='not company']">' no puede ser localizado en la vista padre

Error context:
View `brand_external_layout`
[view_id: 2340, xml_id: brand_external_report_layout.brand_external_layout, model: n/a, parent_id: 213]
Traceback (most recent call last):
  File "/home/usuario/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/usuario/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/usuario/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7fa435ddd160>, 'web.external_layout_standard', ('en_US', False, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuario/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/usuario/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/usuario/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View._read_template at 0x7fa436393280>, frozenset({1, 2, 3, 4, 6, 7, 10, 14, 17, 18, 19, 21, 23, 27, 28, 29, 32, 33, 35, 36, 37, 38, 39, 40, 41, 44, 47, 50, 51, 54, 55, 56, 58, 59, 60, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 81}), 213, ('en_US', False, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 669, in apply_inheritance_specs
    source = apply_inheritance_specs(source, specs_tree,
  File "/home/usuario/odoo/odoo/tools/template_inheritance.py", line 229, in apply_inheritance_specs
    raise ValueError(
ValueError: El elemento '<xpath expr="//t[@t-if='not company']">' no puede ser localizado en la vista padre

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuario/odoo/odoo/addons/base/models/qweb.py", line 359, in get_template
    document = options.get('load', self.load)(template, options)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_qweb.py", line 121, in load
    template = env['ir.ui.view'].read_template(name)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 1071, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-33>", line 2, in _read_template
  File "/home/usuario/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 1063, in _read_template
    arch = self.browse(view_id).read_combined(['arch'])['arch']
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 745, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 694, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/home/usuario/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<xpath expr="//t[@t-if='not company']">' no puede ser localizado en la vista padre

Error context:
View `brand_external_layout`
[view_id: 2340, xml_id: brand_external_report_layout.brand_external_layout, model: n/a, parent_id: 213]

load could not load template
ValueError: El elemento '<xpath expr="//t[@t-if='not company']">' no puede ser localizado en la vista padre

Error context:
View `brand_external_layout`
[view_id: 2340, xml_id: brand_external_report_layout.brand_external_layout, model: n/a, parent_id: 213]
Template: web.external_layout
Path: /t/t[3]

**Comment by sbejaoui** [comment]
Hi,

You shouldn't select `brand_external_layout` as a company layout in Settings>Documents.

The `brand_external_layout` aims to brand any external layout and replace company info by brand ones.

Please refer to the module usage https://github.com/OCA/brand/tree/13.0/brand_external_report_layout#usage

**Comment by abyte20** [comment]
Thanks for answering.

Initially I installed, and did not change anything in Settings (it was external_layout_standard), I did the 4 steps, create the brand with another address and logo, and then create an invoice by selecting the new brand, but when billing the brand is not applied, nothing happens .
How can I show it?

**Comment by abyte20** [comment]
Hi again!
I have put "external_layout_standard" again and it works! I don't know why befor don't work, but now it works.
I can create invoices with the brands and each one has a logo.
Thanks  you, it's really useful

PS: I have a question when creating an order on the ecommerce website, I think it will be more orderly to create a new issue.
